db:
  image: postgres:latest
  ports:
  - "5432:5432"
  volumes_from:
  - data
  env_file: ./docker/.env
web:
  build: .
  ports:
  - "456:80"
  links:
  - db:postgres
  volumes_from:
  - data
  environment:
  - PASSENGER_APP_ENV=development
  - RAILS_ENV=development
  env_file: ./docker/.env
data:
  build: ./docker/data
